odoo-db:
  image: 'philipsahli/postgresql-test:latest'
  environment:
    - DB_NAME=ooo
    - DB_USER=odoo
    - PASSWORD=transformer
  ports:
    - '5432'
odoo:
  image: philipsahli/docker-odoo
  environment:
    - DB_ENV_DB_NAME=odoo
    - DB_ENV_DB_USER=odoo
    - DB_ENV_PASSWORD=transformer
  ports:
    - 8000:80
  volumes:
    - ./website_blog_qotd:/opt/odoo-8.0.0/addons/website_blog_qotd
  links:
    - 'odoo-db:db'

